/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author julian
 */
public class Inicio extends javax.swing.JFrame {

    private Dimension dim;
    
    public Inicio() {
        initComponents();
        setTitle("Inicio");
        
        ImageIcon logo1=new ImageIcon(getClass().getResource("/Imagenes/cliente.png"));
        ImageIcon tamaño=new ImageIcon(logo1.getImage().getScaledInstance(imgCliente.getWidth(), imgCliente.getHeight(), Image.SCALE_DEFAULT));
        imgCliente.setIcon(tamaño);
        
        ImageIcon logo2=new ImageIcon(getClass().getResource("/Imagenes/gear.png"));
        ImageIcon tamaño2=new ImageIcon(logo2.getImage().getScaledInstance(imgComponente.getWidth(), imgComponente.getHeight(), Image.SCALE_DEFAULT));
        imgComponente.setIcon(tamaño2);
        
        ImageIcon logo3=new ImageIcon(getClass().getResource("/Imagenes/power.png"));
        ImageIcon tamaño3=new ImageIcon(logo3.getImage().getScaledInstance(imgEstados.getWidth(), imgEstados.getHeight(), Image.SCALE_DEFAULT));
        imgEstados.setIcon(tamaño3);
        
        ImageIcon logo4=new ImageIcon(getClass().getResource("/Imagenes/administrador.png"));
        ImageIcon tamaño4=new ImageIcon(logo4.getImage().getScaledInstance(imgPerfiles.getWidth(), imgPerfiles.getHeight(), Image.SCALE_DEFAULT));
        imgPerfiles.setIcon(tamaño4);
        
        ImageIcon logo5=new ImageIcon(getClass().getResource("/Imagenes/calendar.png"));
        ImageIcon tamaño5=new ImageIcon(logo5.getImage().getScaledInstance(imgHorarios.getWidth(), imgHorarios.getHeight(), Image.SCALE_DEFAULT));
        imgHorarios.setIcon(tamaño5);
        
        dim = super.getToolkit().getScreenSize();
        super.setSize(dim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ADMINISTRADOR = new javax.swing.JLabel();
        txt_administrador = new javax.swing.JLabel();
        Inicio = new javax.swing.JButton();
        Clientes = new javax.swing.JButton();
        Componentes = new javax.swing.JButton();
        Estados = new javax.swing.JButton();
        Perfiles = new javax.swing.JButton();
        Horarios = new javax.swing.JButton();
        LADO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        imgPerfiles = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        imgCliente = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        imgEstados = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        imgComponente = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        imgHorarios = new javax.swing.JLabel();
        SUPERIOR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADMINISTRADOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrador.png"))); // NOI18N
        jPanel1.add(ADMINISTRADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        txt_administrador.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        txt_administrador.setText("Administrador");
        jPanel1.add(txt_administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        Inicio.setBackground(new java.awt.Color(0, 0, 255));
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Inicio");
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 140, -1));

        Clientes.setBackground(new java.awt.Color(51, 51, 255));
        Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jPanel1.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, -1));

        Componentes.setBackground(new java.awt.Color(51, 51, 255));
        Componentes.setForeground(new java.awt.Color(255, 255, 255));
        Componentes.setText("Componentes");
        Componentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentesActionPerformed(evt);
            }
        });
        jPanel1.add(Componentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, -1));

        Estados.setBackground(new java.awt.Color(51, 51, 255));
        Estados.setForeground(new java.awt.Color(255, 255, 255));
        Estados.setText("Estados");
        Estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadosActionPerformed(evt);
            }
        });
        jPanel1.add(Estados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 140, -1));

        Perfiles.setBackground(new java.awt.Color(51, 51, 255));
        Perfiles.setForeground(new java.awt.Color(255, 255, 255));
        Perfiles.setText("Perfiles");
        jPanel1.add(Perfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 140, -1));

        Horarios.setBackground(new java.awt.Color(51, 51, 255));
        Horarios.setForeground(new java.awt.Color(255, 255, 255));
        Horarios.setText("Horarios");
        jPanel1.add(Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 140, -1));

        LADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lado.png"))); // NOI18N
        LADO.setText("Perfiles");
        jPanel1.add(LADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 200, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 160, 211));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPerfiles, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPerfiles, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 180, 180));

        jPanel4.setBackground(new java.awt.Color(36, 160, 211));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, 180));

        jPanel5.setBackground(new java.awt.Color(36, 160, 211));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imgEstados, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgEstados, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 190, 180));

        jPanel6.setBackground(new java.awt.Color(36, 160, 211));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgComponente, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgComponente, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 190, 180));

        jPanel7.setBackground(new java.awt.Color(36, 160, 211));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 190, 180));

        SUPERIOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/superior.png"))); // NOI18N
        SUPERIOR.setText("jLabel1");
        jPanel2.add(SUPERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1220, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 1, 1190, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        GestionUsuarios gc = new GestionUsuarios();
        gc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClientesActionPerformed

    private void ComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComponentesActionPerformed
        EstadosActualesComponentes gComp = new EstadosActualesComponentes();
        gComp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComponentesActionPerformed

    private void EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADMINISTRADOR;
    private javax.swing.JButton Clientes;
    private javax.swing.JButton Componentes;
    private javax.swing.JButton Estados;
    private javax.swing.JButton Horarios;
    private javax.swing.JButton Inicio;
    private javax.swing.JLabel LADO;
    private javax.swing.JButton Perfiles;
    private javax.swing.JLabel SUPERIOR;
    private javax.swing.JLabel imgCliente;
    private javax.swing.JLabel imgComponente;
    private javax.swing.JLabel imgEstados;
    private javax.swing.JLabel imgHorarios;
    private javax.swing.JLabel imgPerfiles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel txt_administrador;
    // End of variables declaration//GEN-END:variables
}
